/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Breaker;

import java.io.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.SwingUtilities;
import Breaker.VideoTool.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.synth.*;


/**
 *
 * @author a-scott-1
 */
public class BreakView extends JFrame {
   // Class variables
   static File ToConvert = null;
   static File Converted = null;
   static boolean  cleanFileName = true;
   static String Preset = null;
   static String[] PresetList = {"Universal",
                                 "iPod",
                                 "iPhone & iPod Touch",
                                 "iPad",
                                 "AppleTV",
                                 "AppleTV 2",
                                 "Android",
                                 "Android Tablet",
                                 "Normal",
                                 "High Profile"};
   

   /**
    * Creates new form BreakView
    */
   public BreakView() {
      //initLaF();
      initComponents();
   }
   
   private static void initLaF() {
      SynthLookAndFeel lookAndFeel = new SynthLookAndFeel();
            try {
            	
            	// SynthLookAndFeel load() method throws a checked exception
            	// (java.text.ParseException) so it must be handled
            	lookAndFeel.load(BreakView.class.getResourceAsStream("laf.xml"),
                				  BreakView.class);
                UIManager.setLookAndFeel(lookAndFeel);
            } 
            
            catch (ParseException | UnsupportedLookAndFeelException e) {
                System.err.println("Couldn't get specified look and feel ("
                                   + lookAndFeel
                                   + "), for some reason.");
                System.err.println("Using the default look and feel.");
            }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      FileDialog = new javax.swing.JFileChooser();
      dlgWarning = new javax.swing.JDialog();
      lblWarning = new javax.swing.JLabel();
      OptionWindow = new javax.swing.JFrame();
      jSeparator1 = new javax.swing.JSeparator();
      lblLaFSelect = new javax.swing.JLabel();
      btnLaFSelect = new javax.swing.JButton();
      lblCleanFileName = new javax.swing.JLabel();
      btnCleanFileName = new javax.swing.JToggleButton();
      lblJunkData = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      txtboxJunk = new javax.swing.JTextPane();
      btnSelectFiles = new javax.swing.JButton();
      btnDest = new javax.swing.JButton();
      ScrlPaneConversion = new javax.swing.JScrollPane();
      lstConversion = new javax.swing.JList();
      btnOptions = new javax.swing.JButton();
      btnStart = new javax.swing.JButton();

      lblWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

      javax.swing.GroupLayout dlgWarningLayout = new javax.swing.GroupLayout(dlgWarning.getContentPane());
      dlgWarning.getContentPane().setLayout(dlgWarningLayout);
      dlgWarningLayout.setHorizontalGroup(
         dlgWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(dlgWarningLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblWarning, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
            .addContainerGap())
      );
      dlgWarningLayout.setVerticalGroup(
         dlgWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(dlgWarningLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      OptionWindow.setMinimumSize(new java.awt.Dimension(500, 500));

      lblLaFSelect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblLaFSelect.setText("Choose an xml file to use for the theme");

      btnLaFSelect.setText("Select file");

      lblCleanFileName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblCleanFileName.setText("Clean junk from the file name?");

      btnCleanFileName.addChangeListener(new javax.swing.event.ChangeListener() {
         public void stateChanged(javax.swing.event.ChangeEvent evt) {
            btnCleanFileNameStateChanged(evt);
         }
      });

      lblJunkData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblJunkData.setText("Enter below what should be considered file name junk, seperated by commas");

      jScrollPane1.setViewportView(txtboxJunk);

      javax.swing.GroupLayout OptionWindowLayout = new javax.swing.GroupLayout(OptionWindow.getContentPane());
      OptionWindow.getContentPane().setLayout(OptionWindowLayout);
      OptionWindowLayout.setHorizontalGroup(
         OptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jSeparator1)
         .addGroup(OptionWindowLayout.createSequentialGroup()
            .addComponent(lblLaFSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnLaFSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionWindowLayout.createSequentialGroup()
            .addComponent(lblCleanFileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnCleanFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
         .addComponent(jScrollPane1)
         .addGroup(OptionWindowLayout.createSequentialGroup()
            .addComponent(lblJunkData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );
      OptionWindowLayout.setVerticalGroup(
         OptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(OptionWindowLayout.createSequentialGroup()
            .addGroup(OptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lblLaFSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnLaFSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(OptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnCleanFileName)
               .addComponent(lblCleanFileName))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblJunkData)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(170, 170, 170))
      );

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      btnSelectFiles.setText("Click to select files/folders to convert");
      btnSelectFiles.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnSelectFilesMouseClicked(evt);
         }
      });

      btnDest.setText("Click to set converted file destination");
      btnDest.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnDestMouseClicked(evt);
         }
      });

      lstConversion.setModel(new javax.swing.AbstractListModel() {
         String[] strings = { "Universal", "iPod", "iPhone & iPod Touch", "iPad", "AppleTV", "AppleTV 2", "Android", "Android Tablet", "Normal", "High Profile" };
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      lstConversion.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseReleased(java.awt.event.MouseEvent evt) {
            lstConversionMouseReleased(evt);
         }
      });
      ScrlPaneConversion.setViewportView(lstConversion);

      btnOptions.setText("Options");
      btnOptions.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseReleased(java.awt.event.MouseEvent evt) {
            btnOptionsMouseReleased(evt);
         }
      });

      btnStart.setText("Convert");
      btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseReleased(java.awt.event.MouseEvent evt) {
            btnStartMouseReleased(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnDest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(btnSelectFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(ScrlPaneConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnOptions)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(btnSelectFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnDest, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(ScrlPaneConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(btnOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents
   
   private File SelectFile(Component parent, int SelectMode) {
      FileDialog.setFileSelectionMode(SelectMode);
      String ApproveText = "Select...";
      int RetVal = FileDialog.showDialog(parent, ApproveText);
      
      if (RetVal == JFileChooser.APPROVE_OPTION) {
         return FileDialog.getSelectedFile();
      }
      
      else {
         return null;
      }
   }         
   
   private void btnDestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDestMouseClicked
   File Dest = SelectFile(this, JFileChooser.DIRECTORIES_ONLY);
      if (Dest != null) {
         btnDest.setText(Dest.getAbsolutePath());
         Converted = Dest;
      }
   }//GEN-LAST:event_btnDestMouseClicked

   private void btnSelectFilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectFilesMouseClicked
      File Selected = SelectFile(this, JFileChooser.FILES_AND_DIRECTORIES);
      if (Selected != null) {
         if (Selected.isFile()) {
            btnSelectFiles.setText(Selected.getName());
            ToConvert = Selected;
         }
         else if (Selected.isDirectory()) {
            btnSelectFiles.setText(Selected.getAbsolutePath());
            ToConvert = Selected;
         }
      }
   }//GEN-LAST:event_btnSelectFilesMouseClicked

   private void btnStartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseReleased
      // TODO add your handling code here:
      VideoTool VT = new VideoTool();
      VT.ExectuteConvert();
   }//GEN-LAST:event_btnStartMouseReleased

   private void lstConversionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstConversionMouseReleased
      Preset = PresetList[lstConversion.getSelectedIndex()];
   }//GEN-LAST:event_lstConversionMouseReleased

   private void btnOptionsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOptionsMouseReleased
      OptionWindow.show();
      btnCleanFileName.setSelected(true);
      btnCleanFileName.setText("Yes");
   }//GEN-LAST:event_btnOptionsMouseReleased

   private void btnCleanFileNameStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnCleanFileNameStateChanged
      btnCleanFileName.setText(btnCleanFileName.isSelected() ? "Yes" : "No");
      cleanFileName = btnCleanFileName.isSelected();
   }//GEN-LAST:event_btnCleanFileNameStateChanged

   public void SetWarningText(String WarningText) {
      dlgWarning.setVisible(true);
      lblWarning.setText(WarningText);
   }
   
   /**
    */
   public static void main() {
      String lafStr = "laf.xml";
      /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//       */
//      try {
//         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//            if ("Nimbus".equals(info.getName())) {
//               javax.swing.UIManager.setLookAndFeel(info.getClassName());
//               break;
//            }
//         }
//      } catch (ClassNotFoundException ex) {
//         java.util.logging.Logger.getLogger(BreakView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (InstantiationException ex) {
//         java.util.logging.Logger.getLogger(BreakView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (IllegalAccessException ex) {
//         java.util.logging.Logger.getLogger(BreakView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//         java.util.logging.Logger.getLogger(BreakView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      }
       //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            //JFrame.setDefaultLookAndFeelDecorated(true);
            new BreakView().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JFileChooser FileDialog;
   private javax.swing.JFrame OptionWindow;
   private javax.swing.JScrollPane ScrlPaneConversion;
   public static javax.swing.JToggleButton btnCleanFileName;
   private javax.swing.JButton btnDest;
   private javax.swing.JButton btnLaFSelect;
   private javax.swing.JButton btnOptions;
   private javax.swing.JButton btnSelectFiles;
   private javax.swing.JButton btnStart;
   private javax.swing.JDialog dlgWarning;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JLabel lblCleanFileName;
   private javax.swing.JLabel lblJunkData;
   private javax.swing.JLabel lblLaFSelect;
   private javax.swing.JLabel lblWarning;
   private javax.swing.JList lstConversion;
   public static javax.swing.JTextPane txtboxJunk;
   // End of variables declaration//GEN-END:variables
}
