/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Breaker;

import java.io.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.SwingUtilities;
import javax.swing.*;
import Breaker.VideoTool.*;


/**
 *
 * @author a-scott-1
 */
public class BreakView extends javax.swing.JFrame {
   // Class variables
   static File ToConvert = null;
   static File ConvertDest = null;
   static String Preset = null;
   

   /**
    * Creates new form BreakView
    */
   public BreakView() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      FileDialog = new javax.swing.JFileChooser();
      Options = new javax.swing.JOptionPane();
      dlgWarning = new javax.swing.JDialog();
      lblWarning = new javax.swing.JLabel();
      btnSelectFiles = new javax.swing.JButton();
      btnDest = new javax.swing.JButton();
      ScrlPaneConversion = new javax.swing.JScrollPane();
      lstConversion = new javax.swing.JList();
      btnOptions = new javax.swing.JButton();
      btnStart = new javax.swing.JButton();

      lblWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

      javax.swing.GroupLayout dlgWarningLayout = new javax.swing.GroupLayout(dlgWarning.getContentPane());
      dlgWarning.getContentPane().setLayout(dlgWarningLayout);
      dlgWarningLayout.setHorizontalGroup(
         dlgWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(dlgWarningLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblWarning, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
            .addContainerGap())
      );
      dlgWarningLayout.setVerticalGroup(
         dlgWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(dlgWarningLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      btnSelectFiles.setText("Click to select files/folders to convert");
      btnSelectFiles.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnSelectFilesMouseClicked(evt);
         }
      });

      btnDest.setText("Click to set converted file destination");
      btnDest.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnDestMouseClicked(evt);
         }
      });

      lstConversion.setModel(new javax.swing.AbstractListModel() {
         String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      ScrlPaneConversion.setViewportView(lstConversion);

      btnOptions.setText("Options");

      btnStart.setText("Convert");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnDest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(btnSelectFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(ScrlPaneConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnOptions)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(btnSelectFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnDest, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(ScrlPaneConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(btnOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents
   
   private File SelectFile(Component parent, int SelectMode) {
      FileDialog.setFileSelectionMode(SelectMode);
      String ApproveText = "Select...";
      int RetVal = FileDialog.showDialog(parent, ApproveText);
      
      if (RetVal == JFileChooser.APPROVE_OPTION) {
         return FileDialog.getSelectedFile();
      }
      
      else {
         return null;
      }
   }         
   
   private void btnDestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDestMouseClicked
   File Dest = SelectFile(this, JFileChooser.DIRECTORIES_ONLY);
      if (Dest != null) {
         btnDest.setText(Dest.getAbsolutePath());
         ConvertDest = Dest;
      }
   }//GEN-LAST:event_btnDestMouseClicked

   private void btnSelectFilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectFilesMouseClicked
      File Selected = SelectFile(this, JFileChooser.FILES_AND_DIRECTORIES);
      if (Selected != null) {
         if (Selected.isFile()) {
            btnSelectFiles.setText(Selected.getName());
            ToConvert = Selected;
         }
         else if (Selected.isDirectory()) {
            btnSelectFiles.setText(Selected.getAbsolutePath());
            ToConvert = Selected;
         }
      }
   }//GEN-LAST:event_btnSelectFilesMouseClicked

   public void SetWarningText(String WarningText) {
      dlgWarning.setVisible(true);
      lblWarning.setText(WarningText);
   }
   
   /**
    */
   public static void main() {
      /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//       */
//      try {
//         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//            if ("Nimbus".equals(info.getName())) {
//               javax.swing.UIManager.setLookAndFeel(info.getClassName());
//               break;
//            }
//         }
//      } catch (ClassNotFoundException ex) {
//         java.util.logging.Logger.getLogger(BreakView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (InstantiationException ex) {
//         java.util.logging.Logger.getLogger(BreakView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (IllegalAccessException ex) {
//         java.util.logging.Logger.getLogger(BreakView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//         java.util.logging.Logger.getLogger(BreakView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      }
       //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new BreakView().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JFileChooser FileDialog;
   private javax.swing.JOptionPane Options;
   private javax.swing.JScrollPane ScrlPaneConversion;
   private javax.swing.JButton btnDest;
   private javax.swing.JButton btnOptions;
   private javax.swing.JButton btnSelectFiles;
   private javax.swing.JButton btnStart;
   private javax.swing.JDialog dlgWarning;
   private javax.swing.JLabel lblWarning;
   private javax.swing.JList lstConversion;
   // End of variables declaration//GEN-END:variables
}
